# Generated by Django 5.0.1 on 2024-02-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profiles/default_user.png', upload_to='profiles/'),
        ),
    ]
